### Numpy

NumPy is an amazing scientific computing library that is used by numerous other Python Data Science libraries. It contains many mathematical, array and string functions that are extremely useful. Along with all the basic math functions you'll also find them for Linear Algebra, Statistics, Simulation, etc.

I recommend that you use the Jupyter setup I use with Anaconda so that you'll have access to all of NumPys dependencies.

NumPy utilizes vector (1D Arrays) and matrice arrays (2D Arrays).

#### Advantages of numpyh arrays over lists

Performance: NumPy arrays are implemented in C and are more efficient for numerical operations compared to Python lists. The underlying array operations are highly optimized, leading to faster execution of mathematical operations.

Memory Efficiency: NumPy arrays are more memory-efficient than Python lists. The memory layout of NumPy arrays is contiguous, and the data type of each element is fixed, allowing for better memory management. In contrast, Python lists can store elements of different data types, which leads to additional memory overhead.

Vectorization: NumPy supports vectorized operations, which means you can apply operations to entire arrays at once without the need for explicit loops. This leads to concise and readable code and takes advantage of optimized C and Fortran code for these operations.

Broadcasting: NumPy allows for broadcasting, a powerful feature that enables arithmetic operations between arrays of different shapes and sizes. This can simplify code and eliminate the need for explicit loops or element-wise operations.

#### Creation

In [8]:
import numpy as np

list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)
print(np_arr_1)
print(type(np_arr_1))
print(np_arr_1.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
np.arange(1, 10) # using arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Creating n dimentional arrays

In [9]:
np_arr_1 = np.array([1, 2, 3, 4, 5], ndmin =5)
print(np_arr_1)
print(np_arr_1.ndim)

[[[[[1 2 3 4 5]]]]]
5


#### With floats define start, end and number of values

In [12]:
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Creating ones arrays

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Creating Empty arrays

In [18]:
np.empty(4) # Here previous data is filled in the array

array([1., 1., 1., 1.])

#### Creating identity matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

#### Creating arrays with random numbers

In [21]:
np.random.rand(4) # It creates arrays with values between 0 and 1

array([0.3083215 , 0.79204673, 0.85505762, 0.17681684])

In [22]:
np.random.rand(2,5)

array([[0.23787541, 0.22523375, 0.51099439, 0.4400952 , 0.1047542 ],
       [0.79447018, 0.0499384 , 0.65411814, 0.36313423, 0.85946398]])

In [23]:
np.random.randn(5)# It will create array with values close to 0 and will contain values with positive and negative number

array([-0.03928958,  0.64808719, -1.30353039,  0.77370022, -1.96036871])

In [28]:
np.random.ranf(5) # It will create array with values containing 0 and not including 5

array([0.35667793, 0.2014459 , 0.30812767, 0.68685875, 0.80146659])

In [29]:
np.random.randint(5,20,5)  # It will create arrays containg 5 values between 5 and 20

array([ 5, 15, 12, 18,  9])

#### Datatypes in numpy

bool: Boolean (True or False) stored as a byte

int8, int16, int32, int64: Signed integers with different bit depths (8, 16, 32, or 64 bits)

uint8, uint16, uint32, uint64: Unsigned integers with different bit depths (8, 16, 32, or 64 bits)

float16, float32, float64, float128: Floating-point numbers with different precision (16, 32, 64, or 128 bits)

complex64, complex128, complex256: Complex numbers with different precision (64, 128, or 256 bits)

object: Python object type, allowing any Python object to be stored in the array

string_: Variable-length ASCII string type (use S followed by a number for fixed-size strings, e.g., S10 for a 10-character string)

unicode_: Variable-length Unicode string type (use U followed by a number for fixed-size strings, e.g., U10 for a 10-character Unicode string)

In [31]:
arr_bool = np.array([True, False, True])
print("bool array:", arr_bool)
print("Data type:", arr_bool.dtype)
print()

bool array: [ True False  True]
Data type: bool



In [32]:
arr_int8 = np.array([-128, 0, 127], dtype=np.int8)
print("int8 array:", arr_int8)
print("Data type:", arr_int8.dtype)

int8 array: [-128    0  127]
Data type: int8


In [33]:
arr_float16 = np.array([1.0, 2.5, 3.75], dtype=np.float16)
print("float16 array:", arr_float16)
print("Data type:", arr_float16.dtype)
print()

float16 array: [1.   2.5  3.75]
Data type: float16



In [34]:
arr_complex64 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex64)
print("complex64 array:", arr_complex64)
print("Data type:", arr_complex64.dtype)
print()

complex64 array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex64



In [38]:
arr_object = np.array([1, 'hello', [3.14, 2.71]], dtype=object)
print("object array:", arr_object)
print("Data type:", arr_object.dtype)


object array: [1 'hello' list([3.14, 2.71])]
Data type: object


In [39]:
arr_string = np.array(['abc', 'def', 'ghi'], dtype=np.str_)
print("string_ array:", arr_string)
print("Data type:", arr_string.dtype)
print()

string_ array: ['abc' 'def' 'ghi']
Data type: <U3



In [40]:
arr_unicode = np.array(['αβγ', 'δεζ', 'ηθι'], dtype=np.unicode_)
print("unicode_ array:", arr_unicode)
print("Data type:", arr_unicode.dtype)

unicode_ array: ['αβγ' 'δεζ' 'ηθι']
Data type: <U3


In [41]:
# To convert it into any other datatype use astype

#### Shape

In [43]:
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print(var.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [45]:
var.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
var.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array:")
print(original_array)
print("Shape:", original_array.shape)
print()

resized_array = np.resize(original_array, (5, 5))

print("Resized Array:")
print(resized_array)
print("Shape:", resized_array.shape)

Original Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Resized Array:
[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]
 [4 5 6 1 2]
 [3 4 5 6 1]]
Shape: (5, 5)


On resizing the the elements will be added sequentially or truncated accordingly

In [52]:
resized_array.transpose()

array([[1, 6, 5, 4, 3],
       [2, 1, 6, 5, 4],
       [3, 2, 1, 6, 5],
       [4, 3, 2, 1, 6],
       [5, 4, 3, 2, 1]])

In [59]:
# Create a sample array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Resize the array to a new shape
resized_array = np.resize(original_array, (3, 4))

# Swap the axes (transpose the array)
swapped_array = resized_array.swapaxes(0, 1)

# Print the original, resized, and swapped arrays
print("Original Array:")
print(original_array)
print("\nResized Array:")
print(resized_array)
print("\nSwapped (Transposed) Array:")
print(swapped_array)

Original Array:
[[1 2 3]
 [4 5 6]]

Resized Array:
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]

Swapped (Transposed) Array:
[[1 5 3]
 [2 6 4]
 [3 1 5]
 [4 2 6]]


In [55]:
swapped_array.flatten()#row wise

array([1, 5, 3, 2, 6, 4, 3, 1, 5, 4, 2, 6])

In [58]:
swapped_array.flatten('F')#column wise

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [60]:
# Sort rows
swapped_array.sort(axis=1)
print(swapped_array)

[[1 3 5]
 [2 4 6]
 [1 3 5]
 [2 4 6]]


In [61]:
# Sort columns
swapped_array.sort(axis=0)
swapped_array

array([[1, 3, 5],
       [1, 3, 5],
       [2, 4, 6],
       [2, 4, 6]])

#### Arithmetic operation

On 1d arrays

In [64]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Addition
result_addition = array1 + array2
# result_addition = np.add(array1,array2)
print("Addition:")
print(result_addition)

# Subtraction
result_subtraction = array1 - array2
# result_subtraction = np.subtract(array1,array2)
print("\nSubtraction:")
print(result_subtraction)

# Multiplication
result_multiplication = array1 * array2
# result_multiplication = np.multiply(array1,array2)
print("\nMultiplication:")
print(result_multiplication)

# Division
result_division = array1 / array2
# result_division = np.divide(array1,array2)
print("\nDivision:")
print(result_division)

# Element-wise square
result_square = array1**2
# result_square = np.square(array1)
print("\nElement-wise Square:")
print(result_square)

# Element-wise square root
result_sqrt = np.sqrt(array1)
print("\nElement-wise Square Root:")
print(result_sqrt)

# Element-wise exponential
result_exp = np.exp(array1)
print("\nElement-wise Exponential:")
print(result_exp)

# Modulus
result_modulus = np.mod(array1, 3)
print("Modulus (remainder when divided by 3):")
print(result_modulus)

# Power
result_power = np.power(array1, 2)
print("\nPower (square each element):")
print(result_power)

# Reciprocal
result_reciprocal = np.reciprocal(array1.astype(float))  # reciprocal function requires floating-point input
print("\nReciprocal (1/x for each element):")
print(result_reciprocal)

Addition:
[ 7  9 11 13 15]

Subtraction:
[-5 -5 -5 -5 -5]

Multiplication:
[ 6 14 24 36 50]

Division:
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]

Element-wise Square:
[ 1  4  9 16 25]

Element-wise Square Root:
[1.         1.41421356 1.73205081 2.         2.23606798]

Element-wise Exponential:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Modulus (remainder when divided by 3):
[1 2 0 1 2]

Power (square each element):
[ 1  4  9 16 25]

Reciprocal (1/x for each element):
[1.         0.5        0.33333333 0.25       0.2       ]


In [66]:
array = np.array([3, 7, 1, 9, 2, 5])

# Minimum and Maximum
min_value = np.min(array)
max_value = np.max(array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# Index of Minimum and Maximum
argmin_index = np.argmin(array)
argmax_index = np.argmax(array)
print("\nIndex of Minimum Value:", argmin_index)
print("Index of Maximum Value:", argmax_index)

# Sine and Cosine
sin_array = np.sin(array)
cos_array = np.cos(array)
print("\nSine of the Array:")
print(sin_array)
print("\nCosine of the Array:")
print(cos_array)

# Cumulative Sum
cumsum_array = np.cumsum(array)
print("\nCumulative Sum of the Array:")
print(cumsum_array)


Minimum Value: 1
Maximum Value: 9

Index of Minimum Value: 2
Index of Maximum Value: 3

Sine of the Array:
[ 0.14112001  0.6569866   0.84147098  0.41211849  0.90929743 -0.95892427]

Cosine of the Array:
[-0.9899925   0.75390225  0.54030231 -0.91113026 -0.41614684  0.28366219]

Cumulative Sum of the Array:
[ 3 10 11 20 22 27]


On 2d arrays

In [67]:
import numpy as np

# Create two 2D arrays
array1_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
array2_2d = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

# Addition
result_addition_2d = array1_2d + array2_2d
print("Addition (2D):")
print(result_addition_2d)

# Subtraction
result_subtraction_2d = array1_2d - array2_2d
print("\nSubtraction (2D):")
print(result_subtraction_2d)

# Multiplication
result_multiplication_2d = array1_2d * array2_2d
print("\nMultiplication (2D):")
print(result_multiplication_2d)

# Division
result_division_2d = array1_2d / array2_2d
print("\nDivision (2D):")
print(result_division_2d)

# Element-wise square
result_square_2d = array1_2d**2
print("\nElement-wise Square (2D):")
print(result_square_2d)

# Element-wise square root
result_sqrt_2d = np.sqrt(array1_2d)
print("\nElement-wise Square Root (2D):")
print(result_sqrt_2d)

# Element-wise exponential
result_exp_2d = np.exp(array1_2d)
print("\nElement-wise Exponential (2D):")
print(result_exp_2d)

# Modulus
result_modulus_2d = np.mod(array1_2d, 3)
print("\nModulus (remainder when divided by 3) (2D):")
print(result_modulus_2d)

# Power
result_power_2d = np.power(array1_2d, 2)
print("\nPower (square each element) (2D):")
print(result_power_2d)

# Reciprocal
result_reciprocal_2d = np.reciprocal(array1_2d.astype(float))  # reciprocal function requires floating-point input
print("\nReciprocal (1/x for each element) (2D):")
print(result_reciprocal_2d)

# Minimum and Maximum
min_value_2d = np.min(array1_2d)
max_value_2d = np.max(array1_2d)
print("\nMinimum Value (2D):", min_value_2d)
print("Maximum Value (2D):", max_value_2d)

# Index of Minimum and Maximum
argmin_index_2d = np.argmin(array1_2d)
argmax_index_2d = np.argmax(array1_2d)
print("\nIndex of Minimum Value (2D):", argmin_index_2d)
print("Index of Maximum Value (2D):", argmax_index_2d)

# Sine and Cosine
sin_array_2d = np.sin(array1_2d)
cos_array_2d = np.cos(array1_2d)
print("\nSine of the Array (2D):")
print(sin_array_2d)
print("\nCosine of the Array (2D):")
print(cos_array_2d)

# Cumulative Sum
cumsum_array_2d = np.cumsum(array1_2d)
print("\nCumulative Sum of the Array (2D):")
print(cumsum_array_2d)


Addition (2D):
[[12 14 16 18 20]
 [22 24 26 28 30]]

Subtraction (2D):
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]

Multiplication (2D):
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]

Division (2D):
[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444 0.47368421 0.5       ]]

Element-wise Square (2D):
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]

Element-wise Square Root (2D):
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]

Element-wise Exponential (2D):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]]

Modulus (remainder when divided by 3) (2D):
[[1 2 0 1 2]
 [0 1 2 0 1]]

Power (square each element) (2D):
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]

Reciprocal (1/x for each element) (2D):
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.1666666

#### Broadcasting

Broadcasting is a powerful feature in NumPy that allows for performing operations on arrays of different shapes and sizes, making it possible to operate on arrays that would otherwise be incompatible. The smaller array is "broadcast" across the larger array so that they have compatible shapes for element-wise operations.

The basic idea behind broadcasting is to automatically expand the smaller array to have the same shape as the larger array, so that element-wise operations can be performed without requiring explicit replication of the smaller array.

NumPy follows a set of rules to determine whether two arrays are compatible for broadcasting:

Dimension Compatibility Rule:
If the arrays have a different number of dimensions, pad the smaller-dimensional array's shape with ones on its left side.

Size Compatibility Rule:
If, after applying the dimension compatibility rule, the sizes along a particular dimension don't match:
If one of them is 1, it is stretched or "broadcast" along that dimension to match the size of the other.
If neither size is 1 and they differ, broadcasting is not possible, and it raises an error.

In [68]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])

# Broadcasting x and y to perform element-wise addition
result = x + y

print("Array x:")
print(x)
print("\nArray y:")
print(y)
print("\nResult of Broadcasting (x + y):")
print(result)


Array x:
[[1 2 3]
 [4 5 6]]

Array y:
[10 20 30]

Result of Broadcasting (x + y):
[[11 22 33]
 [14 25 36]]


#### Indexing and Slicing

In [72]:
list_1 = [1, 2, 3, 4, 5]
var = np.array(list_1, dtype=np.int8)

var[1]

2

In [76]:
var2 = np.array([[1,2,3],[4,5,6]])
var2[0,2]

3

In [78]:

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Simple slicing
slice_1 = arr_2d[1:3, 1:3]
print("Slice 1:")
print(slice_1)

# Slicing with specific rows and all columns
slice_2 = arr_2d[0:2, :]
print("\nSlice 2:")
print(slice_2)

# Slicing with all rows and specific columns
slice_3 = arr_2d[:, 2:4]
print("\nSlice 3:")
print(slice_3)

# Using negative indices for slicing
slice_4 = arr_2d[-2:, -2:]
print("\nSlice 4:")
print(slice_4)

# Using steps in slicing
slice_5 = arr_2d[::2, ::2]
print("\nSlice 5:")
print(slice_5)

# Use boolean indexing to get values greater than 5 and lesser than 10
filtered_values = arr_2d[(arr_2d > 5) & (arr_2d < 10)]

print("Filtered Values:")
print(filtered_values)

Slice 1:
[[ 6  7]
 [10 11]]

Slice 2:
[[1 2 3 4]
 [5 6 7 8]]

Slice 3:
[[ 3  4]
 [ 7  8]
 [11 12]]

Slice 4:
[[ 7  8]
 [11 12]]

Slice 5:
[[ 1  3]
 [ 9 11]]
Filtered Values:
[6 7 8 9]


In [79]:
# Find uniques
np.unique(arr_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Iteration

In [82]:
var = np.array([[[1,2,3],[4,5,6]]])
var

array([[[1, 2, 3],
        [4, 5, 6]]])

In [83]:
for i in np.nditer(var):
    print(i)

1
2
3
4
5
6


In [84]:
for i in np.nditer(var,flags=['buffered'], op_dtypes = ["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [85]:
for i,d in np.ndenumerate(var):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6


In [86]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])

# Create a copy of the original array
copied_array = original_array.copy()

# Create a view of the original array
viewed_array = original_array.view()

# Modify the elements in the copy and view
copied_array[0] = 99
viewed_array[1] = 88

print("Original Array:", original_array)
print("Copied Array:", copied_array)
print("Viewed Array:", viewed_array)


Original Array: [ 1 88  3  4  5]
Copied Array: [99  2  3  4  5]
Viewed Array: [ 1 88  3  4  5]


#### Join and split function

First make ensure that the data in both the array are equal in numbers

In [88]:
import numpy as np

# 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate along the default axis (axis=0 for 1D arrays)
concatenated_arrays_1d = np.concatenate((array1, array2))
print("Concatenated 1D Arrays:")
print(concatenated_arrays_1d)

# 2D arrays
array2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
array2d_2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along axis 0 (rows)
concatenated_arrays_axis0 = np.concatenate((array2d_1, array2d_2), axis=0)
print("\nConcatenated 2D Arrays along Axis 0:")
print(concatenated_arrays_axis0)

# Concatenate along axis 1 (columns)
concatenated_arrays_axis1 = np.concatenate((array2d_1, array2d_2), axis=1)
print("\nConcatenated 2D Arrays along Axis 1:")
print(concatenated_arrays_axis1)


Concatenated 1D Arrays:
[1 2 3 4 5 6]

Concatenated 2D Arrays along Axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated 2D Arrays along Axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Using stack

In [90]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack along a new axis (axis=0)
stacked_arrays_axis0 = np.stack((array1, array2), axis=0)
print("Stacked 1D Arrays along Axis 0:")
print(stacked_arrays_axis0)

# Horizontal stacking
hstack_result = np.hstack((array1, array2))
print("Horizontal Stack:")
print(hstack_result)

# Vertical stacking
vstack_result = np.vstack((array1, array2))
print("\nVertical Stack:")
print(vstack_result)

# Depth-wise stacking of 2D arrays
dstack_result = np.dstack((array1, array2))
print("\nDepth-wise Stack:")
print(dstack_result)

Stacked 1D Arrays along Axis 0:
[[1 2 3]
 [4 5 6]]
Horizontal Stack:
[1 2 3 4 5 6]

Vertical Stack:
[[1 2 3]
 [4 5 6]]

Depth-wise Stack:
[[[1 4]
  [2 5]
  [3 6]]]


In [91]:
import numpy as np

# Create a 1D array
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the 1D array into three equal parts
split_result_1d = np.split(array1d, 3)
print("Split 1D Array:")
print(split_result_1d)

# Create a 2D array
array2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Split the 2D array along the columns (axis=1)
hsplit_result = np.hsplit(array2d, 2)
print("\nHorizontal Split (axis=1) of 2D Array:")
print(hsplit_result)

# Split the 2D array along the rows (axis=0)
vsplit_result = np.vsplit(array2d, 3)
print("\nVertical Split (axis=0) of 2D Array:")
print(vsplit_result)

# Create a 3D array
array3d = np.array([[[1, 2, 3], [4, 5, 6]],
                    [[7, 8, 9], [10, 11, 12]],
                    [[13, 14, 15], [16, 17, 18]]])

# Split the 3D array along the depth (axis=2)
dsplit_result = np.dsplit(array3d, 3)
print("\nDepth-wise Split (axis=2) of 3D Array:")
print(dsplit_result)


Split 1D Array:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Horizontal Split (axis=1) of 2D Array:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]

Vertical Split (axis=0) of 2D Array:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

Depth-wise Split (axis=2) of 3D Array:
[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]],

       [[13],
        [16]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]],

       [[15],
        [18]]])]


#### Search

In [92]:
import numpy as np

# Create an array
arr = np.array([1, 5, 2, 7, 3, 8, 4, 6])

# Find indices where elements are greater than 5
indices = np.where(arr > 5)

print("Array:")
print(arr)
print("Indices where elements are greater than 5:")
print(indices)


Array:
[1 5 2 7 3 8 4 6]
Indices where elements are greater than 5:
(array([3, 5, 7]),)


In [93]:
import numpy as np

# Create a sorted array
arr_sorted = np.array([2, 4, 5, 7, 9])

# Find the index where 6 should be inserted to maintain order
index_insert = np.searchsorted(arr_sorted, 6)

print("Sorted Array:")
print(arr_sorted)
print("Index where 6 should be inserted to maintain order:", index_insert)


Sorted Array:
[2 4 5 7 9]
Index where 6 should be inserted to maintain order: 3


#### Sorting

In [94]:
import numpy as np

# Create an unsorted array
arr_unsorted = np.array([4, 2, 7, 1, 9])

# Sort the array
arr_sorted = np.sort(arr_unsorted)

print("Unsorted Array:")
print(arr_unsorted)
print("Sorted Array:")
print(arr_sorted)


Unsorted Array:
[4 2 7 1 9]
Sorted Array:
[1 2 4 7 9]


#### Insertion

In [95]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Insert a row with values [10, 11, 12] at index 1
arr_2d_inserted_row = np.insert(arr_2d, 1, [10, 11, 12], axis=0)

# Insert a column with values [99, 88, 77] at index 2
arr_2d_inserted_col = np.insert(arr_2d, 2, [99, 88, 77], axis=1)

print("Original 2D Array:")
print(arr_2d)

print("\n2D Array after Inserting Row at Index 1:")
print(arr_2d_inserted_row)

print("\n2D Array after Inserting Column at Index 2:")
print(arr_2d_inserted_col)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2D Array after Inserting Row at Index 1:
[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]

2D Array after Inserting Column at Index 2:
[[ 1  2 99  3]
 [ 4  5 88  6]
 [ 7  8 77  9]]


In [96]:
import numpy as np

# Example 1: Deleting elements from a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Delete the element at index 2
arr_1d_deleted = np.delete(arr_1d, 2)

print("Original 1D Array:")
print(arr_1d)
print("\n1D Array after Deleting Element at Index 2:")
print(arr_1d_deleted)

# Example 2: Deleting rows and columns from a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Delete the row at index 1
arr_2d_deleted_row = np.delete(arr_2d, 1, axis=0)

# Delete the column at index 2
arr_2d_deleted_col = np.delete(arr_2d, 2, axis=1)

print("\nOriginal 2D Array:")
print(arr_2d)
print("\n2D Array after Deleting Row at Index 1:")
print(arr_2d_deleted_row)
print("\n2D Array after Deleting Column at Index 2:")
print(arr_2d_deleted_col)

Original 1D Array:
[1 2 3 4 5]

1D Array after Deleting Element at Index 2:
[1 2 4 5]

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2D Array after Deleting Row at Index 1:
[[1 2 3]
 [7 8 9]]

2D Array after Deleting Column at Index 2:
[[1 2]
 [4 5]
 [7 8]]


#### Matrix Functions

Dot Product

In [98]:
matrix1 = np.matrix([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.matrix([[7, 8],
                    [9, 10],
                    [11, 12]])

# Compute the dot product using numpy.dot()
dot_product_result = np.dot(matrix1, matrix2)

# Alternatively, you can use the @ operator
# dot_product_result = matrix1 @ matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nDot Product Result:")
print(dot_product_result)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Dot Product Result:
[[ 58  64]
 [139 154]]


In [99]:
import numpy as np

# Create three matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

matrix3 = np.array([[13, 14],
                    [15, 16]])

# Compute the dot product of three matrices using numpy.linalg.multi_dot()
dot_product_result = np.linalg.multi_dot([matrix1, matrix2, matrix3])

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix 3:")
print(matrix3)

print("\nDot Product Result:")
print(dot_product_result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix 3:
[[13 14]
 [15 16]]

Dot Product Result:
[[1714 1836]
 [4117 4410]]


In [4]:
import numpy as np
from numpy.linalg import eig

arr_5 = np.array([[4, -2], [1, 1]])
arr_12 = np.array([[1, 2], [3, 4]])

# Eigenvectors and Eigenvalues
eigenvalues, eigenvectors = eig(arr_5)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [6]:
from numpy.linalg import norm

# Vector Norm (Euclidean norm)
norm_result = norm(arr_5)
print("\nVector Norm (Euclidean norm):")
print(norm_result)


Vector Norm (Euclidean norm):
4.69041575982343


In [7]:
from numpy.linalg import inv

# Multiplicative Inverse (Inverse of a matrix)
inverse_matrix = inv(arr_5)
print("\nMultiplicative Inverse of the matrix:")
print(inverse_matrix)


Multiplicative Inverse of the matrix:
[[ 0.16666667  0.33333333]
 [-0.16666667  0.66666667]]


In [8]:
from numpy.linalg import cond

# Condition number of a matrix
condition_number = cond(arr_5)
print("\nCondition number of the matrix:")
print(condition_number)


Condition number of the matrix:
3.3699240762154825


In [20]:
from numpy.linalg import det

# Determinant of a matrix
determinant_result = det(arr_12)
print("\nDeterminant of the matrix:")
print(determinant_result)


Determinant of the matrix:
-2.0000000000000004


In [ ]:
# Raise matrix to the power of n
# Given [[a, b], [c, d]]
# [[a² + bc, ab +db], [ac + dc, d² + bc]
LA.matrix_power(arr_5, 2)


#### Comparision Functions

In [21]:
carr_1 = np.array([2, 3])
carr_2 = np.array([3, 2])
# Returns boolean based on whether arr_1 value Comparison arr_2 value
print(np.greater(carr_1, carr_2))
print(np.greater_equal(carr_1, carr_2))
print(np.less(carr_1, carr_2))
print(np.less_equal(carr_1, carr_2))
print(np.not_equal(carr_1, carr_2))
print(np.equal(carr_1, carr_2))

[False  True]
[False  True]
[ True False]
[ True False]
[ True  True]
[False False]


In [22]:
pip install numpy-financial

Note: you may need to restart the kernel to use updated packages.


#### Financial Funcitons

In [23]:
import numpy_financial as npf

# Compute future value of $400 investment every month
# with an annual rate of 8% after 10 years
print(npf.fv(.08/12, 10*12, -400, -400))


74066.27016650053


In [24]:
# Calculate interest portion of payment on a loan of $3,000
# at 9.25% per year compounded monthly
# Period of loan (year)
period = np.arange(1*12) + 1
principle = 3000.00
# Interest Payment
ipmt = npf.ipmt(0.0925/12, period, 1*12, principle)
print(ipmt)
# Principle Payment
ppmt = npf.ppmt(0.0925/12, period, 1*12, principle)
print(ppmt)
for payment in period:
    index = payment - 1
    principle = principle + ppmt[index]
    print(f"{payment}   {np.round(ppmt[index], 2)}    {np.round(ipmt[index],2)}    {np.round(principle, 2)}")

[-23.125      -21.27825789 -19.41728047 -17.54195802 -15.65217996
 -13.74783486 -11.82881043  -9.89499353  -7.94627011  -5.98252529
  -4.00364327  -2.00950737]
[-239.5773551  -241.42409721 -243.28507463 -245.16039708 -247.05017514
 -248.95452024 -250.87354467 -252.80736157 -254.75608499 -256.71982981
 -258.69871183 -260.69284773]
1   -239.58    -23.12    2760.42
2   -241.42    -21.28    2519.0
3   -243.29    -19.42    2275.71
4   -245.16    -17.54    2030.55
5   -247.05    -15.65    1783.5
6   -248.95    -13.75    1534.55
7   -250.87    -11.83    1283.67
8   -252.81    -9.89    1030.87
9   -254.76    -7.95    776.11
10   -256.72    -5.98    519.39
11   -258.7    -4.0    260.69
12   -260.69    -2.01    0.0


In [25]:
# Compute number of payments to pay off $3,000 if you paid
# $150 per month with an interest rate of 9.25%
np.round(npf.nper(0.0925/12, -150, 3000.00), 2)

21.8

In [26]:
# Calculate net present value of cash flows of $4,000, $5,000
# $6,000, $7,000 after $15,000 investment with .08 rate per period
npf.npv(0.08, [-15000, 4000, 5000, 6000, 7000]).round(2)

2898.6

In [28]:
# Given [[a, b], [c, d]]
# [[a² + bc, ab +db], [ac + dc, d² + bc]

import numpy as np
from numpy.linalg import matrix_power as mp

# Example matrix
arr_5 = np.array([[1, 2], [3, 4]])

# Calculate matrix_power
result_matrix = mp(arr_5, 2)

print("Original Matrix:")
print(arr_5)

print("\nResult Matrix (Matrix Squared):")
print(result_matrix)

Original Matrix:
[[1 2]
 [3 4]]

Result Matrix (Matrix Squared):
[[ 7 10]
 [15 22]]
